import { Box, Button, TextField, Typography } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import React, { ChangeEvent, FormEvent, useState } from 'react'
import Logo from '../../../public/Images/ACSlogo.svg'

type FormState = {
  password: string
  confirmPassword: string
}

const FgPassword: React.FC = () => {
  const [data, setData] = useState<FormState>({
    password: '',
    confirmPassword: '',
  })

  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    setData({
      ...data,
      [e.target.name]: e.target.value,
    })
  }

  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    console.log('Data submitted:', data)
    setData({
      password: '',
      confirmPassword: '',
    })
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        component="main"
        sx={{
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          height: '100vh',
          padding: '0 20px',
        }}
      >
        <Box
          component="article"
          sx={{
            textAlign: 'center',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            maxWidth: 600,
            width: '100%',
          }}
        >
          <Image src={Logo} alt="ACS Logo" width={100} height={100} />
          <Typography variant="h1" sx={{ my: 2 }}>
            กรอกรหัสใหม่ของคุณ
          </Typography>{' '}
          <Box
            component="form"
            onSubmit={handleSubmit}
            sx={{
              width: '100%',
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              mx: 10,
              gap: 2,
            }}
          >
            <TextField
              fullWidth
              id="password"
              name="password"
              label="รหัสผ่านใหม่"
              variant="outlined"
              color="primary"
              type="password"
              value={data.password}
              onChange={handleChange}
            />
            <TextField
              fullWidth
              id="confirmPassword"
              name="confirmPassword"
              label="ยืนยันรหัสผ่านใหม่"
              variant="outlined"
              color="primary"
              type="password"
              value={data.confirmPassword}
              onChange={handleChange}
            />
            <Button
              type="submit"
              variant="contained"
              color="primary"
              size="large"
              sx={{ mt: 2, width: '30%' }}
            >
              เปลี่ยนรหัสผ่าน
            </Button>
          </Box>
        </Box>
      </Box>
    </>
  )
}

export default FgPassword
